config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'relationships/followings'
  get 'relationships/followers'
  
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  get "search" => "searches#search"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true  
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = @book.id
    comment.save
    render 'book_comments'
  end

  def destroy
    BookComment.find(params[:id]).destroy
    @book = Book.find(params[:book_id])
    render 'book_comments'
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_book_comment.html.erb
<%= form_with model: [book, @book_comment] do |f| %>
  <div class="form-group">
    <%= f.text_area :comment, class: "form-control book_comment border-secondary" %>
  </div>
  <div class="form-group">
    <%= f.submit "送信", class: "btn  btn-outline-secondary text-dark font-weight-bold" %>
  </div>
<% end %>

app/views/book_comments/_book_comments_count.html.erb
<%= "コメント数: #{book.book_comments.count}" %>

app/views/book_comments/_book_comments_index.html.erb
<% book.book_comments.each do |book_comment| %>
  <table class="table">
    <td class="col-md-3">
      <%= link_to(book_comment.user) do %>
        <%= image_tag book_comment.user.get_profile_image(50, 50) %><br>
        <%= book_comment.user.name %>
      <% end %>
    </td>
    <td class="col-md-3"><%= book_comment.comment %></td>
    <td>
      <% if book_comment.user == current_user %>
        <%= link_to 'Destroy', book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger pull-right" %>
      <% end %>
    </td>
  </table>
<% end %>

app/views/book_comments/_count.html.erb
<%= "コメント数: #{book.book_comments.count}" %>

app/views/book_comments/_form.html.erb
<%= form_with model: [book, @book_comment], local: false do |f| %>
  <div class="form-group">
    <%= f.text_area :comment, class: "form-control book_comment border-secondary" %>
  </div>
  <div class="form-group">
    <%= f.submit "送信", class: "btn  btn-outline-secondary text-dark font-weight-bold" %>
  </div>
<% end %>

app/views/book_comments/_index.html.erb
<table class="table">
  <% book.book_comments.each do |book_comment| %>
  <tr>
    <td class="col-md-3">
      <%= link_to(book_comment.user) do %>
        <%= image_tag book_comment.user.get_profile_image(50, 50) %><br>
        <%= book_comment.user.name %>
      <% end %>
    </td>
    <td class="col-md-3"><%= book_comment.comment %></td>
    <td>
      <% if book_comment.user == current_user %>
        <%= link_to 'Destroy', book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn btn-danger pull-right" %>
      <% end %>
    </td>
  </tr>
  <% end %>
</table>

app/views/book_comments/book_comments.js.erb
$("#comments_area").html("<%= j(render 'book_comments/index', book: @book) %>");

$("textarea").val('');